version: '3.1'

services:
  mongo:
    image: mongo
    env_file:
      - .env.local
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mobileStore
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
volumes:
  mongo-data:
    driver: local
